### ISSUE TITLE
Need a error page for "Request failed with status code 400"

### ISSUE THREAD

**Issue by rayanfer32** [rayanfer32/nexus-explorer-next#202]
**Describe the bug**

For Testnet routes when accessing DAO

**To Reproduce**

1. Go to
2. Click on
3. Scroll down to

**Expected behavior**

**Device Details (please complete the following information):**

- [ ] Desktop
- [ ] Mobile

- Device name:
- OS:
- Browser: chrome
- Version: -

**Screenshots**

- none

**Additional context**

- none

**Comment by shrivatsabhat** [comment]
@rayanfer32 isn't it related to the https://github.com/rayanfer32/nexus-explorer-next/issues/203 bug ticket ?

**Comment by rayanfer32** [comment]
> @rayanfer32 isn't it related to the #203 bug ticket ?

Yea I think we no longer need this
